name: $(SourceBranchName)-$(SourceVersion)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - release-azure-pipelines-app.yml

resources:
  repositories:
  - repository: Templates
    type: git
    name: Templates

variables:
- group: Registry

stages:
- template: kanban-pushandbuild.yml@Templates